---
- hosts: all
  become: true
  pre_tasks:

  - name: Updating Ubuntu Server
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

  - name: Updating Centos
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

#- hosts: Execute Ubuntu
#  become: true
#  roles:
#    - Ubuntu

- hosts: Execute CentOS
  become: true
  roles:
    - CentOS
